server:
  port: 8088

spring:
  application:
    name: msvc-apigateway
  cloud:
    gateway:
      routes:

        # Ruta para Inventario
        - id: inventario-service
          uri: lb://msvc-inventario  # Asegúrate que coincida con el nombre en Eureka
          predicates:
            - Path=/api/v1/inventario/**
          filters:
            - StripPrefix=2  # Remueve /api/v1 del path antes de enviar al microservicio
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        # Ruta para detalle producto solicitud
        - id: detalle-producto-solicitud-route
          uri: lb://msvc-solicitud  # Ajusta según tu servicio real
          predicates:
            - Path=/api/v1/detalleproductosolicitud/**
          filters:
            - StripPrefix=2

        # Ruta para solicitud
        - id: solicitud-route
          uri: lb://msvc-solicitud
          predicates:
            - Path=/api/v1/solicitud/**
          filters:
            - StripPrefix=2

        # Ruta para producto
        - id: producto-route
          uri: lb://msvc-inventario  # Ajusta según tu servicio real
          predicates:
            - Path=/api/v1/producto/**
          filters:
            - StripPrefix=2

        # Ruta para movimiento
        - id: movimiento-route
          uri: lb://msvc-inventario  # Ajusta según tu servicio real
          predicates:
            - Path=/api/v1/movimiento/**
          filters:
            - StripPrefix=2

        # Ruta para usuario
        - id: usuario-route
          uri: lb://msvc-usuario  # Ajusta según tu servicio real
          predicates:
            - Path=/api/v1/usuario/**
          filters:
            - StripPrefix=2

        # Ruta para rol
        - id: rol-route
          uri: lb://msvc-usuario  # Ajusta según tu servicio real
          predicates:
            - Path=/api/v1/rol/**
          filters:
            - StripPrefix=2

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always