server:
  port: 8088

spring:
  application:
    name: msvc-apigateway
  cloud:
    gateway:
      routes:
        # Ruta para el microservicio de Usuarios
        - id: msvc-usuario-route
          uri: http://localhost:8084 # Dirección del microservicio
          predicates:
            - Path=/api/usuarios/** # Cualquier petición que empiece con /api/usuarios/ será redirigida

        # Ruta para el microservicio de Productos
        - id: msvc-producto-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/productos/**

        # Ruta para el microservicio de Solicitudes
        - id: msvc-solicitud-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/solicitudes/**

        # Ruta para el microservicio de Inventario
        - id: msvc-inventario-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/inventario/**

        # ... y así sucesivamente para los demás microservicios

        - id: msvc-detalle-solicitud-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/detalles-solicitud/**

        - id: msvc-rol-route
          uri: http://localhost:8086
          predicates:
            - Path=/api/roles/**

        - id: msvc-movimiento-route
          uri: http://localhost:8087
          predicates:
            - Path=/api/movimientos/**